import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "../globals.css";
import { SidebarNav } from "@/components/ui/sidebar-nav";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const sidebarNavItems = [
  {
    title: "Start of Turn",
    href: "/rounds/start",
  },
  {
    title: "Hero Phase",
    href: "/rounds/hero",
  },
  {
    title: "Movement Phase",
    href: "/rounds/movement",
  },
  {
    title: "Shooting Phase",
    href: "/rounds/shooting",
  },
  {
    title: "Charge Phase",
    href: "/rounds/charge",
  },
  {
    title: "Combat Phase",
    href: "/rounds/combat",
  },
  {
    title: "End of Turn",
    href: "/rounds/end",
  },
]

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (

      <div className="flex flex-col space-y-8 lg:flex-row lg:space-x-12 lg:space-y-0">
          <aside className="-mx-4 lg:w-1/5">
            <SidebarNav items={sidebarNavItems} />
          </aside>
          <div className="flex-1 lg:max-w-2xl">{children}</div>
        </div>

  );
}
